### ISSUE TITLE
hello from frictionless data team

### ISSUE THREAD

**Issue by lwinfree** [neuromat/nes#4]
Hi! I wanted to introduce you to our developers: Adrià (@amercader) & Evgeny (@roll)
(Feel free to close this issue 😃 )

**Comment by carlosribas** [comment]
Hello Lilly, Adrià and Evgeny, nice to meet you all!

**Comment by amercader** [comment]
Hi @carlosribas! Looking forward to collaborate

**Comment by roll** [comment]
Hi @carlosribas! Nice to meet you!

**Comment by carlosribas** [comment]
Let me use this issue to introduce the developers of our research center who will work on this project: Cassiano (@caco13 ) and Éder (@Ederporto ).

**Comment by roll** [comment]
Hi @caco13 @Ederporto :+1:

**Comment by caco13** [comment]
Hello @roll and @amercader nice to meet you.
